- id: '1683021101609'
  alias: FullBackup_2am
  description: ''
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - service: hassio.backup_full
    data:
      compressed: true
  mode: single
