- id: '1683021101609'
  alias: FullBackup_2am
  description: ''
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1683835557958'
  alias: Allumer TV
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fe4f15a80ba31864517d52cd9a8b0f0
    type: action
    subtype: 1_single
    discovery_id: 0xa4c138243c3ac00a action_1_single
  condition: []
  action:
  - type: turn_on
    device_id: e2374c1ae90a01e1b23c2cd0e32ef0fe
    entity_id: switch.multiprisetv_l1
    domain: switch
  - service: script.ambiance_tv
    data: {}
  mode: single
- id: '1683966944851'
  alias: Coupure TV quand freebox éteinte
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: a744a962360332b9705e8f8af18a2eab
    entity_id: 1d3e677fc01c388a39bb9ea03b8cce3b
    domain: remote
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: or
    conditions:
    - condition: device
      device_id: 310431d68dafb9ebcc0d9691c14bd65b
      domain: media_player
      entity_id: cb510071aa3b9ffed27491191571435e
      type: is_idle
    - condition: device
      device_id: 310431d68dafb9ebcc0d9691c14bd65b
      domain: media_player
      entity_id: cb510071aa3b9ffed27491191571435e
      type: is_off
  action:
  - type: turn_off
    device_id: e2374c1ae90a01e1b23c2cd0e32ef0fe
    entity_id: switch.multiprisetv_l1
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.lumiere_eteintes
    metadata: {}
  mode: single
- id: '1684324252372'
  alias: Allumer Wii
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fe4f15a80ba31864517d52cd9a8b0f0
    type: action
    subtype: 1_double
    discovery_id: 0xa4c138243c3ac00a action_1_double
  condition: []
  action:
  - type: turn_on
    device_id: e2374c1ae90a01e1b23c2cd0e32ef0fe
    entity_id: switch.multiprisetv_l3
    domain: switch
  mode: single
- id: '1684325104545'
  alias: Eteindre Wii
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fe4f15a80ba31864517d52cd9a8b0f0
    type: action
    subtype: 1_hold
    discovery_id: 0xa4c138243c3ac00a action_1_hold
  condition: []
  action:
  - type: turn_off
    device_id: e2374c1ae90a01e1b23c2cd0e32ef0fe
    entity_id: switch.multiprisetv_l3
    domain: switch
  mode: single
- id: '1684436711504'
  alias: Interrupteur Lampe Salon
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fe4f15a80ba31864517d52cd9a8b0f0
    type: action
    subtype: 2_single
    discovery_id: 0xa4c138243c3ac00a action_2_single
  condition: []
  action:
  - type: toggle
    device_id: 724d8e206f9a96ab64a2963602edf631
    entity_id: switch.priselampesalon
    domain: switch
  mode: single
- id: '1684436752236'
  alias: Interrupteur Lumiere TV
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fe4f15a80ba31864517d52cd9a8b0f0
    type: action
    subtype: 2_double
    discovery_id: 0xa4c138243c3ac00a action_2_double
  condition: []
  action:
  - type: toggle
    device_id: e2374c1ae90a01e1b23c2cd0e32ef0fe
    entity_id: switch.multiprisetv_l2
    domain: switch
  mode: single
- id: '1685705691752'
  alias: Interrupteurs Ampoules Canape/TV
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fe4f15a80ba31864517d52cd9a8b0f0
    type: action
    subtype: 3_single
    discovery_id: 0xa4c138243c3ac00a action_3_single
  condition: []
  action:
  - type: toggle
    device_id: 3ccd1e364e4c2b67cf6a868a267f974e
    entity_id: light.lampecanape
    domain: light
  - type: toggle
    device_id: 0b2b1855831c6d2016813eb9680fb845
    entity_id: light.lampetele
    domain: light
  mode: single
- id: '1685705743413'
  alias: Interrupteur Ampoules Buffet/Flechettes
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fe4f15a80ba31864517d52cd9a8b0f0
    type: action
    subtype: 3_double
    discovery_id: 0xa4c138243c3ac00a action_3_double
  condition: []
  action:
  - type: toggle
    device_id: c0dae5d1a5199f4d4ffa5d2dfb50cbcf
    entity_id: light.lampeflechettes
    domain: light
  - type: toggle
    device_id: 133fada812512009cb33b927f854837f
    entity_id: light.lampebuffet
    domain: light
  mode: single
- id: '1685890678142'
  alias: Ambiance TV on Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  - platform: device
    device_id: a744a962360332b9705e8f8af18a2eab
    domain: media_player
    entity_id: media_player.freebox_player_pop_2
    type: turned_on
  condition: []
  action:
  - service: script.ambiance_tv
    data: {}
  mode: single
- id: '1685895561368'
  alias: MAL_Notif_Arrêt
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.washing_machine
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: notify.mobile_app_sm_a505fn
    data:
      message: MAL Terminée -> va étendre
  mode: single
