
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
automation script: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
person: !include persons.yaml
group: !include groups.yaml
rest: !include rest.yaml
cover: !include cover.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    temp-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:lightbulb-multiple-outline
      show_in_sidebar: true
      filename: dashboards/global.yaml
    config-yaml:
      mode: yaml
      title: Config
      icon: mdi:hammer-wrench
      show_in_sidebar: true
      filename: dashboards/config.yaml
      require_admin: true

calendar:
  - platform: caldav
    username: !secret syno_user
    password: !secret syno_password
    url: !secret caldav_url

template:
  - binary_sensor:
      - name: "Washing Machine"
        delay_off:
          minutes: 5
        device_class: running
        state: >
          {{ states('sensor.prisemal_power') | default(0) | float > 0 }}
  - binary_sensor:
      - name: "soleil face Est"
        state: >
          {{ (state_attr('sun.sun', 'elevation') > 8)
           and (state_attr('sun.sun', 'elevation') < 60)
           and (state_attr('sun.sun', 'azimuth') > 0)
           and (state_attr('sun.sun', 'azimuth') < 154 ) }}
  - binary_sensor:
      - name: "soleil face Sud"
        state: >
          {{ (state_attr('sun.sun', 'elevation') > 0)
           and (state_attr('sun.sun', 'elevation') < 60)
           and (state_attr('sun.sun', 'azimuth') > 78)
           and (state_attr('sun.sun', 'azimuth') < 258 ) }}
  - binary_sensor:
      - name: "soleil face Ouest"
        state: >
          {{ (state_attr('sun.sun', 'elevation') > 6.5)
           and (state_attr('sun.sun', 'elevation') < 60)
           and (state_attr('sun.sun', 'azimuth') > 176)
           and (state_attr('sun.sun', 'azimuth') < 348 ) }}
  - binary_sensor:
      - name: "Jour Dehors"
        state: >
          {{ (state_attr('sun.sun', 'elevation') > -6) }}
  - sensor:
      - name: Sun Elevation
        unit_of_measurement: "°"
        state: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
  - sensor:
      - name: Sun Azimuth
        unit_of_measurement: "°"
        state: "{{ '%+.1f'|format(state_attr('sun.sun', 'azimuth')) }}" 
  - binary_sensor:
      - name: vacances_scolaires_aujourdhui
        unique_id: binary_sensor.vacances_scolaires_aujourdhui
        icon: mdi:calendar-today
        state: |-
          {% set aujourdhui = now().strftime('%Y-%m-%d')%}
          {% if aujourdhui < state_attr('sensor.vacances_scolaires', 'start_date') or aujourdhui > state_attr('sensor.vacances_scolaires', 'end_date') %}
          false
          {% else %} 
          true
          {% endif %}
  - binary_sensor:
      - name: jourTravail
        unique_id: binary_sensor.jour_travail_aujourdhui
        icon: mdi:calendar-today
        state: |-
          {{ is_state('binary_sensor.vacances_scolaires_aujourdhui','off')
          and
          is_state('binary_sensor.ouvrableaujourdhui','on')
          }}
  - sensor:
      - name: "Volume de Gaz"
        unique_id: sensor.gaz_volume
        unit_of_measurement: 'm³'
        state: "{{ states('input_number.gaz_counter') | int / 1000 | round(3) }}"
        device_class: gas
        state_class: total_increasing
  - sensor:
      - name: "Volume d'Eau'"
        unique_id: sensor.water_volume
        unit_of_measurement: 'm³'
        state: "{{ states('input_number.water_counter') | int / 1000 | round(3) }}"
        device_class: water
        state_class: total_increasing

input_number:
  gaz_counter :
    name: gaz_counter
    icon: mdi:gas-cylinder
    min: 0
    max: 100000000000
  water_counter :
    name: water_counter
    icon: mdi:water
    min: 0
    max: 100000000000

input_select: 
  modevolets:
    name: Mode des Volets
    options:
      - Manuel
      - Presence
      - Ete
      - Hiver

utility_meter:
  gaz_total_usage_daily:
    source: sensor.gaz_volume
    cycle: daily
  gaz_total_usage_weekly:
    source: sensor.gaz_volume
    cycle: weekly
  gaz_total_usage_monthly:
    source: sensor.gaz_volume
    cycle: monthly
  gaz_total_usage_quarterly:
    source: sensor.gaz_volume
    cycle: quarterly
  gaz_total_usage_yearly:
    source: sensor.gaz_volume
    cycle: yearly
  water_total_usage_daily:
    source: sensor.water_volume
    cycle: daily
  water_total_usage_weekly:
    source: sensor.water_volume
    cycle: weekly
  water_total_usage_monthly:
    source: sensor.water_volume
    cycle: monthly
  water_total_usage_quarterly:
    source: sensor.water_volume
    cycle: quarterly
  water_total_usage_yearly:
    source: sensor.water_volume
    cycle: yearly