
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Temperatures
      icon: mdi:temperature-celsius
      show_in_sidebar: true
      filename: dashboards/dashboards.yaml 
    lights-yaml:
      mode: yaml
      title: Lumières
      icon: mdi:lightbulb-multiple-outline
      show_in_sidebar: true
      filename: dashboards/lights.yaml
    temp-yaml:
      mode: yaml
      title: Températures
      icon: mdi:lightbulb-multiple-outline
      show_in_sidebar: true
      filename: dashboards/temp-global.yaml
    covers-yaml:
      mode: yaml
      title: Volets
      icon: mdi:window-shutter
      show_in_sidebar: true
      filename: dashboards/covers.yaml
    config-yaml:
      mode: yaml
      title: Config
      icon: mdi:hammer-wrench
      show_in_sidebar: true
      filename: dashboards/config.yaml
      require_admin: true

calendar:
  - platform: caldav
    username: !secret syno_user
    password: !secret syno_password
    url: !secret caldav_url

template:
  - binary_sensor:
      - name: "Washing Machine"
        delay_off:
          minutes: 5
        device_class: running
        state: >
          {{ states('sensor.prisemal_power')|float > 0 }}
  - sensor:
      - name: Sun Elevation
        unit_of_measurement: "°"
        state: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
  - sensor:
      - name: Sun Azimuth
        unit_of_measurement: "°"
        state: "{{ '%+.1f'|format(state_attr('sun.sun', 'azimuth')) }}"
