
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
person: !include persons.yaml
group: !include groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    temp-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:lightbulb-multiple-outline
      show_in_sidebar: true
      filename: dashboards/global.yaml
    config-yaml:
      mode: yaml
      title: Config
      icon: mdi:hammer-wrench
      show_in_sidebar: true
      filename: dashboards/config.yaml
      require_admin: true

calendar:
  - platform: caldav
    username: !secret syno_user
    password: !secret syno_password
    url: !secret caldav_url

template:
  - binary_sensor:
      - name: "Washing Machine"
        delay_off:
          minutes: 5
        device_class: running
        state: >
          {{ states('sensor.prisemal_power') | default(0) | float > 0 }}
  - sensor:
      - name: Sun Elevation
        unit_of_measurement: "°"
        state: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
  - sensor:
      - name: Sun Azimuth
        unit_of_measurement: "°"
        state: "{{ '%+.1f'|format(state_attr('sun.sun', 'azimuth')) }}"

input_select: 
  modevolets:
    name: Mode des Volets
    options:
      - Manuel 
      - Ete
      - Hiver

binary_sensor: 
  - platform: threshold
    name: "soleil face Ouest"
    upper: 340
    lower: 160
    entity_id: sensor.sun_azimuth
  - platform: threshold
    name: "soleil face Est"
    upper: 160
    lower: 0
    entity_id: sensor.sun_azimuth
  - platform: threshold
    name: "soleil face Sud"
    upper: 250
    lower: 70
    entity_id: sensor.sun_azimuth
