- platform: group
  name: Volets Etage
  entities:
  - cover.volet_roulant_gaetan
  - cover.volet_roulant_romain
  - cover.volet_roulant_bureau
  - cover.volet_roulant_salle_jeux
- platform: group
  name: Volets Etage Facade Est
  entities:
  - cover.volet_roulant_gaetan
  - cover.volet_roulant_salle_jeux
- platform: group
  name: Volets RDC Facade Est
  entities:
  - cover.volet_roulant_salon
- platform: group
  name: Volets Etage Facade Ouest
  entities:
  - cover.volet_roulant_romain
  - cover.volet_roulant_bureau
- platform: group
  name: Volets RDC Facade Ouest
  entities:
  - cover.volet_roulant_parents